doctrine:
  dbal:
    driver: 'pdo_pgsql'
    server_version: '11'
    dbname:               '%env(resolve:POSTGRES_DB)%'
    host:                 db
    port:                 5432
    user:                 '%env(resolve:POSTGRES_USER)%'
    password:             '%env(resolve:POSTGRES_PASSWORD)%'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
