version: '2'

services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 8035:80
    volumes:
      - ./:/src
      - ./docker/nginx/conf.d/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    restart: always
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /src
    volumes:
      - ./:/src
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
    links:
      - db

  db:
    build:
      context: ./docker/postgres/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - pgdata4:/var/lib/postgresql/data


volumes:
  pgdata4:
    driver: local
